using Reimaginate.DataHub.SharedModels.Requests.CLI;

namespace Reimaginate.DataHub.Requests.Internal.ProcessSplitDataHubEntityAlternateKey;

public class ProcessSplitDataHubEntityAlternateKeyResponse : SplitDataHubEntityAlternateKeyResponse;
