<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\framework\Reimaginate.DataHub\Reimaginate.DataHub.csproj" />
    <ProjectReference Include="..\..\framework\Reimaginate.DataHub.AspNetCore\Reimaginate.DataHub.AspNetCore.csproj" />
    <ProjectReference Include="..\..\framework\Reimaginate.DataHub.SharedModels\Reimaginate.DataHub.SharedModels.csproj" />
  </ItemGroup>

</Project>
